FROM golang:1.9.1

RUN apt-get update -qq

# install zsh
RUN apt-get install -y zsh
RUN git clone https://github.com/robbyrussell/oh-my-zsh ~/.oh-my-zsh
RUN wget -O /root/.zshrc https://raw.githubusercontent.com/niten2/dotfiles/master/files/zshrc

RUN mkdir /go/src/go-todo-api
ADD . /go/src/go-todo-api
WORKDIR /go/src/go-todo-api

RUN go get ./...
